Create tasks from question
WaitThatShouldntWork/InferGPT pull request #38
Opened 2024-04-23 12:53 UTC by hsauve-scottlogic

## Description

A goal/intention is now broken down into up to 5 tasks

## Changelog
- Created a create_tasks_agent that breakdowns a question into up to 5 tasks
- Updated director code to call create_tasks_agent

2024-04-23 13:26 UTC, harryBedfordSL commented on backend/agents/create_tasks_agent.py
> +    return(response)
is there a reason why we're using a tuple as the return type here? Reading the method name `create_tasks` makes me think some sort of array / list will be returned

2024-04-23 15:35 UTC, philbaxter requested changes
I know return types can be inferred, but if we specify them in one place, we should most likely be consistent and do it in the others too

2024-04-23 15:35 UTC, philbaxter commented on backend/director.py
>  def question(question):
should we specify return type here aswell? str?

2024-04-23 15:35 UTC, philbaxter commented on backend/director.py
> +def determine_intention(question):
similarly specify return type?

2024-04-24 10:00 UTC, philbaxter approved these changes

2024-04-24 10:06 UTC, harryBedfordSL approved these changes

2024-04-24 10:07 UTC, merged