Feature/create chart generator agent
WaitThatShouldntWork/InferGPT pull request #85
Opened 2024-08-13 09:29 UTC by hsauve-scottlogic

## Description

Implement ChartGeneratorAgent that generates and executes chart code using Matplotlib

## Changelog

- Edit intent agent prompt
- Create ChartGeneratorAgent that generates code, sanitises it and executes it
- Add method to Connection Manager to send chart via websocket
- Add MessageType in frontend
- Edit chat component in the frontend to display message with IMAGE MessageType

2024-08-13 09:42 UTC, philbaxter requested changes
Good work, a couple of comments.

2024-08-13 09:42 UTC, philbaxter commented on backend/src/agents/chart_generator_agent.py
> +        await connection_manager.send_chart({"type": "image", "data": image_data})
Should the agent be sending the chart to the frontend, or, should that be the job of the answer agent, meaning we should probably put the chart on the scratchpad.

2024-08-13 09:42 UTC, philbaxter commented on backend/src/agents/chart_generator_agent.py
> +        fig.savefig(output_path)
Why dont we just keep this in memory? I also dont see anywhere where we clean up the file we have created once we are done with it.

2024-08-23 09:20 UTC, gaganahluwalia commented on backend/requirements.txt
> +pillow
Please include the version of this library.

2024-08-23 09:23 UTC, gaganahluwalia commented on backend/src/agents/chart_generator_agent.py
> +
Pleas delete this extra line.

2024-08-23 09:24 UTC, gaganahluwalia commented on backend/src/agents/chart_generator_agent.py
> +@tool(
Please include model and llm as parameters as well.

2024-08-23 09:28 UTC, gaganahluwalia requested changes
As your PR includes the changes related to env.yml to .env file. Could you please revert the changes made in the main README.md file as well.

2024-08-27 09:37 UTC, gaganahluwalia approved these changes

2024-08-27 11:16 UTC, gaganahluwalia approved these changes

2024-08-28 08:24 UTC, SvetA1395 approved these changes

2024-08-28 09:42 UTC, merged